# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy relevant files to the container
COPY ./web.py /app/

# Install required packages
RUN pip install --no-cache-dir gradio Pillow

# Expose the port for Gradio web interface
EXPOSE 7860

# Run the Gradio app
CMD ["python", "web.py"]
