# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy relevant files to the container
COPY ./api.py /app/
COPY ./autocrop /app/autocrop
COPY ./models /app/models
COPY ./requirements.txt /app/

# Install required packages
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose the port the app runs on
EXPOSE 5555

# Run the API with Uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "5555"]
